### ISSUE TITLE
Probably typo in assert

### ISSUE THREAD

**Issue by serzero2007** [statgen/savvy#33]
Here:
```cpp
template <typename AggregateT>
    AggregateT dot_slow(const self_type& other, AggregateT ret) const
    {
      assert(size_ = other.size_);
      ...
      return ret;
    }
```
Probably must be `==` instead of `=`.

https://github.com/statgen/savvy/blob/82fb57602ccabb23ba5a686444102e842c382d28/include/savvy/compressed_vector.hpp#L424

**Comment by jonathonl** [comment]
Thanks for reporting. This has been fixed with https://github.com/statgen/savvy/commit/5d0cd9da476223e2bbe1c85d02601fbe148aadbb.
