### ISSUE TITLE
no warning if sample-ids-file is missing

### ISSUE THREAD

**Issue by ilarsf** [statgen/savvy#5]
Hi, Jonathon,

`sav export --sample-ids-file XXX` will output the whole data if the --sample-ids-file is missing (I had a typo in the file name and no warning message showed up).

Thanks,
Lars

**Comment by jonathonl** [comment]
So to clarify, you ran `sav export --sample-ids-file <input.sav>` accidentally but meant to run `sav export --sample-ids-file <ids.txt> <input.sav>`?

**Comment by ilarsf** [comment]
I ran `sav export --sample-ids-file <ids.txt> <input.sav>` but the <ids.txt> file was actually misspelled, i.e. missing.

**Comment by jonathonl** [comment]
I see. That will be an easy fix. Thanks for reporting.
